### ISSUE TITLE
Attempt to call a nil value "SyncMoney"

### ISSUE THREAD

**Issue by jvstin2k** [project-error/qb-pefcl#13]
So I just installed the pefcl and qb-pefcl and set it up as it is shown in the readme. Somehow I still get an error 

[script:qb-pefcl] SCRIPT ERROR: @qb-pefcl/server.lua:121: attempt to call a nil value (field 'SyncMoney')

I added the SyncMoney function to qb-core/server/player.lua and also edited the other functions. 

qb-pefcl is started after qb-core and pefcl.

**Comment by planeklm** [comment]
I had this error, it should be more clear in the README.md about where to place it.

But anyway here is where you should place it:
In player.lua, search 'function self.Functions.UpdatePlayerData()', and under it place the SyncMoney snippet.

![image](https://github.com/project-error/qb-pefcl/assets/91488137/3636ef48-b912-44c0-992e-ff3b3ed70329)

**Comment by planeklm** [comment]
Hope that helped!

**Comment by jvstin2k** [comment]
> 
It works now, thank you! 

It kinda makes sence that it has to be "placed" there but since there was nothing else shown in the readme I just placed it at the bottom of the player.lua. 

Thanks ;)
